# j_vals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
j_vals: [0, 1, 2, 3, 4, 5, 6]
T_vals: [1, 2, 3, 4, 5, 8]
r_cost: 0.0
feas_tol: 1.0e-4
time_limit: 300
x0_mins: [-1.]
x0_maxes: [1.]
x_feas_mins: [-1.0]
x_feas_maxes: [1.0]
u_bound: 2 #0.1
# Bilinear system: x+[0] = a00*x[0] + u + b*u*x[0]
#                  x+[1] = a11*x[1] + a10*x[0]
a00: 0.9
a10: 0.5
a11: 0.7
b: 0.0 #0.2
