K: 1               # number of closed-loop steps to verify
T_vals: [2, 3, 5] #[2, 3, 5, 10]   # MPC horizons
dt: 0.1
r: .01          # control cost weight
u_bound: 10.0      # control bound [-u_bound, u_bound]
x_mins: [-1]    # initial state set X_0
x_maxes: [1]
rho_max: 4.0      # maximum decay rate to search
tol: 0.001         # bisection tolerance on rho
mip_gap: 0.01     # 1% MIP gap for termination
time_limit: 300
