# T_vals: [2, 5, 10, 20]
# n_ilqr_iters: [1, 2, 3, 5]
# dt: .05
# r: 0.001
# time_limit: 1000
# rho_max: 5
# x_mins: [-2]
# x_maxes: [2]
# tol: 1e-4

T_vals: [1, 2, 5, 10, 12]
n_ilqr_iters: [1] #, 2] #, 3, 5]
dt: 0.01 #.025
r: 0.00 #.0001 #0.001 #1 #0.0001 #0.00 #0.0001
time_limit: 1000
rho_max: 5
x_mins: [-3.]
x_maxes: [3.]
tol: 1e-4
mass: 1
length: 1
nu: 0.0