T_vals: [1, 2, 3, 4, 5, 8, 10]
u_range_vals: [0.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0]  # min(US) ~= 35.33, keep below that
r_vals: [0.0] #, 0.1, 1.0]
dt: 1 #1.0
feas_tol: 1.0e-4
time_limit: 1000
dual_bound: 50.0
x0_nominal: null  # null -> use the center of the box constraints
